export enum ROUTE_TAB {
  TAB = 'TAB',
  HOME_TAB = 'HOME_TAB',
  PROJECT_TAB = 'PROJECT_TAB',
  FUNCTION_TAB = 'FUNCTION_TAB',
  INBOX_TAB = 'INBOX_TAB',
  PROFILE_TAB = 'PROFILE_TAB',
}
export enum ROUTE_AUTH {
  INTRO = 'INTRO',
  LOGIN = 'LOGIN',
  SIGN_IN_PASSWORD = 'SIGN_IN_PASSWORD',
  SIGN_UP = 'SIGN_UP',
  FILL_PROFILE = 'FILL_PROFILE',
  FORGOT_PASSWORD = 'FORGOT_PASSWORD',
}

export enum ROUTE_MAIN {
  ROUTE_MAIN = 'ROUTE_MAIN',
}
